### ISSUE TITLE
Have the option to set magento_dir on the node as an attribute

### ISSUE THREAD

**Issue by rgonzale** [rackspace-cookbooks/magentostack#226]
I have a customer who wants his document root to be named something else other than magento.  Also, his code deploys with the magento document root being several directory levels down from the root of the deployment.

**Comment by martinb3** [comment]
I'm sure we can change the name from `magento` to something arbitrary. I'm not sure we can change the place the code deploys, without stepping on other files the stack also deploys, like modman. Can you give us the concrete paths he's using, and what the repo looks like (in general) so we can be sure we support the scenario you're running into?

**Comment by rgonzale** [comment]
I changed the magento_dir in magento_install.rb so that his code deploys to
/var/www/html/optimus.  His document root is several directory levels lower so I symlinked it in the chef wrapper cookbook 

https://github.com/AutomationSupport/3299905-pos_portal

/var/www/html/optimus/applications/php/magento/enterprise to /var/www/html/magento

**Comment by martinb3** [comment]
Perfect, thanks! A concrete example will help us write a test so that we're sure it works.

**Comment by martinb3** [comment]
I believe this issue is no longer active/relevant. Closing. Please correct me if I'm wrong.
